dist: xenial
language: csharp
solution: Microting.EformMonitoringBase.sln
mono: none
dotnet: 3.1.101
addons:
  chrome: stable
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet restore
  - dotnet build Microting.EformMonitoringBase.sln
  - dotnet test -v n Microting.eFormMonitoringBase.Integration.Tests/Microting.eFormMonitoringBase.Integration.Tests.csproj
  - dotnet test -v n Microting.eFormMonitoringBase.Unit.Tests/Microting.eFormMonitoringBase.Unit.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.EformMonitoringBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-monitoring-base/Microting.EformMonitoringBase/artifacts/Microting.EformMonitoringBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
