dist: xenial
branches:
  only:
    - master
language: csharp
solution: Microting.EformMonitoringBase.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.EformMonitoringBase.sln
  - dotnet test -v n Microting.EformMonitoringBase.Integration.Tests/Microting.EformMonitoringBase.Integration.Tests.csproj
  - dotnet test -v n Microting.EformMonitoringBase.Unit.Tests/Microting.EformMonitoringBase.Unit.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.EformMonitoringBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-monitoring-base/Microting.eFormTrashInspectionBase/artifacts/Microting.EformMonitoringBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
